### PR TITLE
:warning: Add 500 page

### PR DESCRIPTION
**Pull request by neilbmclaughlin**
PR for comment only.

Notes: the html still refers to assets in an application directory.
I think that best practice for an error page to be served by Akamai
is for the assests to be inline.

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
@mcheung-nhs - assuming the styling does need to be inlined would you be able to help me with that?

**Comment by mcheung-nhs** [comment]
Can we have assets uploaded to akamai?

**Comment by mcheung-nhs** [comment]
Just spoke to Paul H and we can upload assets to Akamai if that makes things easier. So we just need to copy the appropriate css and img folders from the connecting-to-services repo.

**Comment by neilbmclaughlin** [comment]
So following discussions on Slack we are going to create a minimalist error page with no dependancies on external images, css or js. This will be served up when the  application is unavailable.

Consider if this should be served up be Azure or Akamai.

**Comment by neilbmclaughlin** [comment]
@mcheung-nhs - would you be OK to pick this up?

As we discussed yesterday the aim is to have a stand-alone server error page which does not depend on the app and will be served if the app is unavailable or any 50x error is generated by the app. The design was lifted from Si's repo.

**Comment by mcheung-nhs** [comment]
@neilbmclaughlin - No problems, will pick this up

**Comment by mcheung-nhs** [comment]
Styling and images added, ready for review

**Pull request merged**
